Port-CountedPtr (#53)
* Updated and cleaned CountedPtr and tests.

Updated and cleaned CountedPtr and tests.

* Addressed various compilation warnings.  Adjusted access specifier spacing.

Removed errant @params.  Suppressed -Wweak-vtables warnings for testing classes, commented out offending sample classes.

Unindented access specifiers by one level.

* Fixed incorrect warning suppressions, removed 0 as null pointer uses

Removed two instances of 0 as a null pointer in favor of nullptr.

Fixed -Wweak-vtables suppressions using the correct name this time.

Added Wpadding suppression.

* Removed incorrect tparam, expanded padding warning suppression

added FooExternal to the -Wpadding suppression.

Removed CountedPointerCastingState tparam which did not need to exist.

* Removed @internal tags

* Suppressed VC warning 4435

Suppressed warning about inheritance from a virtual base potentially changing object layout under /vd2

* Expanded casting tests

* Minor documentation adjustments.

* Removed covariant return types to placate msvc.

Stopgap/test measure to see if removing the covariant return types in GetMostDerived will allow compilation in msvc without error C2250 (ambiguous inheritance).

* Change of 0 -> false.

* Changed dynamic cast failure test to not provoke irrelevant warnings hopefully.

* Suppresed VC Warning 4437

* Reverted warning 4437 suppression, selectively activated vtordisp

* Changed 0 pointers to nullptrs, Various minor doc and readability changes

* Fixed guards that did not adhere to present convention.

* Minor documentation fixes.

* Removed body of unusable cast for readability/simplicity

* Cleaned up vtordisp workaround, removed unnecessary indentation

* Converted typedefs to using

* Fixed test argument ordering.

* Minor documentation changes

* More missing periods

* Port of CountedPtr benchmarks.

* Added include for testing classes.

* Added noexcept to test class constructors.

* Commented out tests that could reasonably induce warnings/failure.

* Reset time markers between tests.

* Reverted ineffective timing changes, commented out unstable test.

* Cosmetic changes to TestLog output